### ISSUE TITLE
 Improve Mermaid Diagram UX to Support Full-Screen View

### ISSUE THREAD

**Issue by ahmedkhan25** [jacob-ai-bot/jacob#341]
# Improve Mermaid Diagram UX to Support Full-Screen View

**@kleneway** - Loving the current functionality with the Mermaid diagrams,  (also used AI to document this )
have a suggestion to improve usability!

Currently, the Mermaid diagram is displayed as a fixed window in the top right corner of the code visualizer. This small view limits the readability and interactivity of the diagrams, especially for more complex code relationships. I propose making the Mermaid diagram **full-screen** to improve the user experience and enhance the ease of navigating the generated diagrams.

## Description
The existing Mermaid diagram component in the code visualizer is constrained to a small, fixed area on the screen, which can make it challenging to analyze complex diagrams in detail or easily copy the rendered content.

To address this, I propose adding functionality to allow the diagram to be viewed in a **full-screen mode**. This would provide the user with more space to analyze intricate diagrams, make the visualization more usable, and facilitate easier copying of the Mermaid diagram output.

### 1. Add Full-Screen Toggle for Mermaid Diagrams
- Introduce a **full-screen button** for the Mermaid diagram.
- Allow users to click this button to **expand the diagram to occupy the entire screen**.
- The button should be located in a prominent place near the current diagram window.

**Implementation Idea**:
```tsx
<button onClick={() => setFullScreenMode(true)}>Full Screen</button>
```
- Use `state` to toggle between full-screen and standard view modes.
- Consider using a library like `react-fullscreen` to simplify this functionality.

### 2. Update Mermaid Component to Support Full-Screen Mode
- Update the `Mermaid` component to utilize conditional styling that adapts based on whether **full-screen mode** is active.
- Modify the existing `div` container for the diagram to support dynamic resizing.

**Current Mermaid Component** (excerpt):
```tsx
const Mermaid: React.FC<MermaidProps> = ({ chart, theme }) => {
  const mermaidRef = useRef<HTMLDivElement>(null);
  const [hideDiagram, setHideDiagram] = React.useState(false);
  const [isFullScreen, setFullScreenMode] = React.useState(false);

  return (
    <div
      ref={mermaidRef}
      className={`rounded bg-white p-2 text-xs shadow-sm dark:bg-gray-800 ${isFullScreen ? 'full-screen-class' : ''}`}
    />
  );
};
```
- Define a **CSS class** (`full-screen-class`) that adjusts the dimensions to take up the entire viewport.

### 3. Add Copy Functionality for the Mermaid Diagram
- Add a **copy button** that allows users to easily copy the **Mermaid code** used to generate the diagram.
- This functionality should be intuitive, providing users with a convenient way to capture the code behind the visual representation.

**Copy Button Implementation**:
```tsx
<button onClick={() => navigator.clipboard.writeText(chart)}>Copy Mermaid Code</button>
```
- Ensure this button is visible both in full-screen and standard modes.

## Expected Benefits
- **Improved Usability**: Full-screen mode will make it easier for developers to view and analyze complex diagrams.
- **Enhanced Interactivity**: Full-screen support enables smoother navigation through larger diagrams without constraints.
- **Increased Productivity**: Users can copy the diagram code effortlessly, enabling reuse or sharing for documentation and collaboration.

## Additional Notes
- **Ensure Responsiveness**: Full-screen mode should adapt well across different screen sizes.
- **Provide a Close Button**: In full-screen mode, include a close button to easily return to the standard view.
- **Accessibility**: Make sure that buttons for toggling full-screen and copying code are accessible and keyboard-friendly.

---

@jacob-ai-bot --skip-build

**Comment by kleneway** [comment]
Just completed this, it's deploying now. Great idea, thanks!
