### ISSUE TITLE
Feature: Image Upload in Chat Interface

### ISSUE THREAD

**Issue by kleneway** [jacob-ai-bot/jacob#40]
### Feature: Image Upload in Chat Interface

**Description:**
Add a new button to the chat interface that allows users to upload an image. The image will be sent to an existing API endpoint, and the returned URL will be saved and passed along with future chat messages to the backend.

**Requirements:**
- Add an upload button to the chat interface.
- Open a file picker dialog when the button is clicked.
- Send the selected image to the existing API endpoint.
- Save the returned URL and pass it along with future chat messages.
- Display an error message using a toast notification if the upload fails.
- Validate the image before uploading (must be under 20MB and either PNG or JPEG).
- Place the upload button to the left of the "send message" button (the up arrow).
- Handle multiple image uploads in quick succession.
- Show an error message if a non-image file is uploaded.
- Set a loading state to true during the upload and back to false once the upload is complete.

#### Files to Update:
- `src/app/dashboard/[org]/[repo]/[developer]/components/chat/ChatMessage.tsx`
- `src/app/dashboard/[org]/[repo]/[developer]/components/chat/Chat.tsx`

**Acceptance Criteria:**
- [ ] Upload button is added to the chat interface.
- [ ] File picker dialog opens on button click.
- [ ] Image is sent to the API endpoint and URL is returned.
- [ ] URL is saved and passed along with future chat messages.
- [ ] Error message is displayed using a toast notification if the upload fails.
- [ ] Image validation is implemented (under 20MB and either PNG or JPEG).
- [ ] Upload button is placed to the left of the "send message" button.
- [ ] Multiple image uploads are handled gracefully.
- [ ] Error message is shown if a non-image file is uploaded.
- [ ] Loading state is managed correctly during the upload process.

@jacob-ai-bot

**Comment by cpirich** [comment]
@jacob-ai-bot build
