### ISSUE TITLE
Add User table to the database

### ISSUE THREAD

**Issue by kleneway** [jacob-ai-bot/jacob#61]
We need to capture a few basic pieces of information for the web portal in the short term, and will need it for future features such as (eventually) name, subscription status, etc.. We can keep this as minimal as possible to streamline the onboarding and mitigate security concerns. 

Fields:
- [ ] GitHub Username
- [ ] Email
- [ ] Onboarding Status
- [ ] isActive
- [ ] Timestamps

Steps
- [ ] Create a new file `src/server/db/tables/users.table.ts`
- [ ] Use a similar style to `projects.table.ts` to create an orchid-orm table
- [ ] Add the new `Users` table to the `src/server/db/db.ts` db config object
- [ ] Create a new migration in the `src/server/db/migrations` folder
- [ ] Run `npm run db migrate` to create the table in the database

**Comment by cpirich** [comment]
Resolved with these changes
* https://github.com/jacob-ai-bot/jacob/pull/65
* https://github.com/jacob-ai-bot/jacob/commit/95b857ea12b01dc92c5f523b9173cb2cb20f2111
